var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/calorieWatcher/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">9th September 2019</p> '
+ '<ul><li>' + zImp + 'the food search list can now be scrolled.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">8th September 2019</p> '
+ '<ul><li>' + zBug + 'foods added just before selecting new day (without closing and reopening the app) did not clear from the list.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">5th September 2019</p> '
+ '<ul><li>' + zImp + 'Removed the 0 on add food dialogue, so you can just type in the amount of the food right away.'
+ '</li><li>' + zImp + 'Add Food dialogue improved to be more intuitive.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd September 2019</p> '
+ '<ul><li>' + zImp + 'A few more foods added, and a few more improvements under the hood.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">1st September 2019</p> '
+ '<ul><li>' + zImp + 'A few new foods added, and a few improvements under the hood.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">31st August 2019</p> '
+ '<ul><li>' + zBug + 'New Day should now wipe the previous day&apos;s food list.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">28th August 2019</p> '
+ '<ul><li>' + zNew + 'New project uploaded to GitHub!'
+ '</li></ul>'
+ '<p>I&apos;ve had this kicking about for a few years, and it is '
+ 'finally time to realease it into the wild.'
+ '</p>'
+ '<hr>'
;
