var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/calorieWatcher/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">31st August 2019</p> '
+ '<ul><li>' + zBug + 'New Day should now wipe the previous day\'s food list.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">28th August 2019</p> '
+ '<ul><li>' + zNew + 'New project uploaded to GitHub!'
+ '</li></ul>'
+ '<p>I&apos;ve had this kicking about for a few years, and it is '
+ 'finally time to realease it into the wild.'
+ '</p>'
+ '<hr>'
;
