var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/calorieWatcher/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">4th September 2019</p> '
+ '<ul><li>' + zNew + 'The webapp didn\'t update the globalfiles serviceWorker in 2 days, so this update is mostly to do with the globalscript "base files", updating should now be great with being able to manually check for an update (settings>app changeLog), and also toast popups letting you know the progress of any popups, along with a restart button to start using the updated version stright away :D I hope to make updating the food list on it\'s own sometime once the project has matured, but still lot\'s to do yet!'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd September 2019</p> '
+ '<ul><li>' + zImp + 'A few more foods added, and a few more improvements under the hood.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">1st September 2019</p> '
+ '<ul><li>' + zImp + 'A few new foods added, and a few improvements under the hood.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">31st August 2019</p> '
+ '<ul><li>' + zBug + 'New Day should now wipe the previous day\'s food list.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">28th August 2019</p> '
+ '<ul><li>' + zNew + 'New project uploaded to GitHub!'
+ '</li></ul>'
+ '<p>I&apos;ve had this kicking about for a few years, and it is '
+ 'finally time to realease it into the wild.'
+ '</p>'
+ '<hr>'
;
